# Generated by Django 3.1.7 on 2021-03-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='location',
            new_name='location_post',
        ),
    ]
