# Generated by Django 3.2 on 2021-09-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210921_2240'),
        ('posts', '0002_auto_20210328_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Gender_prefer',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.yatru'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tour_date',
            field=models.DateField(),
        ),
    ]
