# Generated by Django 3.2 on 2021-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210921_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recentpic',
            field=models.ImageField(default=1, upload_to='photo/'),
            preserve_default=False,
        ),
    ]
