# Generated by Django 3.2 on 2021-09-21 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatru',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='yatru',
            name='insta',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='yatru',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='yatru',
            name='bio',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='yatru',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
